### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by cosmicdan** [InflamedSebi/cmpf#2]
Curse changed some stuff and it will now return a 403 error when you send a request.

I tried hacking in a User-Agent string to something matching a modern browser to no avail. I've no idea what else it could be.

**Comment by InflamedSebi** [comment]
I'm backpacking right now, and I only have my cell phone, so it'll have to wait till Christmas.

**Comment by cosmicdan** [comment]
No problem, just giving a heads up. Enjoy your trip :D

**Comment by InflamedSebi** [comment]
Curse was blocking all connections from non-browser clients. You might want to delete all files (*.cache, *.ini) inside the cache folder plus sub-directories, since some formats changed due to the other changes.
